Add PATH Gateway deployment
pokt-network/helm-charts pull request #44
Opened 2024-12-03 17:57 UTC by red-0ne

Add `PATH Gateway` charts.

This PR is required to make [[LocalNet] Add Path to LocalNet](https://github.com/pokt-network/poktroll/pull/879) CI tests to pass.

2024-12-03 23:52 UTC, Olshansk approved these changes

2024-12-04 22:20 UTC, Olshansk commented
@red-0ne Can we merge this in?

2024-12-04 22:59 UTC, Olshansk requested changes
@red-0ne This only "removes appgate server" configs. 

1. If this is intended -> please update title + description.
2. If it's missing files -> please account for that

2024-12-05 21:27 UTC, Olshansk approved these changes

2024-12-09 16:38 UTC, red-0ne commented
Will merge after https://github.com/pokt-network/poktroll/pull/879

2024-12-10 05:50 UTC, merged